[workspace]
members = [
    # shared
    "common",

    # text/input processing
    "rhead",
    "rwc",

    # file/directory management
    "rtouch",

    # whatever else i feel like
    "rcal",
]
resolver="1"

