[package]
name = "rcal"
version = "1.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
string-builder = "0.2.0"
common = { path = "../common" }

[[bin]]
name = "cal"
path = "src/main.rs"
