[package]
name = "rwc"
version = "1.0.11"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name="wc"
path = "src/main.rs"
